### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 128 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by Dmitry-99** [Beckschen/TransUNet#101]
Hello everyone! I am getting the error when try to make a prediction: 
```
RuntimeError                              Traceback (most recent call last)
Input In [10], in <cell line: 2>()
      4 x, y = x.to(device), y.to(device)
      5 optimizer.zero_grad()  
----> 6 y_pred = model(x)
      7 print(y_pred.shape, y.shape)
      8 loss = criterion(y_pred, y)

File ~/work/smp/segm_venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

Input In [4], in ViTHuBMAP.forward(self, x)
      9 def forward(self, x):
---> 10     img_segs = self.model(x)
     12     return img_segs

File ~/work/smp/segm_venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/work/smp/./TransUNet/networks/vit_seg_modeling.py:389, in VisionTransformer.forward(self, x)
    387     x = x.repeat(1,3,1,1)
    388 x, attn_weights, features = self.transformer(x)  # (B, n_patch, hidden)
--> 389 x = self.decoder(x, features)
    390 logits = self.segmentation_head(x)
    391 return logits

File ~/work/smp/segm_venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/work/smp/./TransUNet/networks/vit_seg_modeling.py:366, in DecoderCup.forward(self, hidden_states, features)
    364     else:
    365         skip = None
--> 366     x = decoder_block(x, skip=skip)
    367 return x

File ~/work/smp/segm_venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File ~/work/smp/./TransUNet/networks/vit_seg_modeling.py:312, in DecoderBlock.forward(self, x, skip)
    310 x = self.up(x)
    311 if skip is not None:
--> 312     x = torch.cat([x, skip], dim=1)
    313 x = self.conv1(x)
    314 x = self.conv2(x)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 128 for tensor number 1 in the list.
```

Images have a size - (BatchSize, 3, 1024, 1024).
ViT config:
```
activation: softmax
classifier: seg
decoder_channels: !!python/tuple
- 256
- 128
- 64
- 16
hidden_size: 768
n_classes: 4
n_skip: 3
patch_size: 16
patches:
  grid: !!python/tuple
  - 15
  - 15
  size: !!python/tuple
  - 16
  - 16
pretrained_path: ./R50+ViT-B_16.npz
representation_size: null
resnet:
  num_layers: !!python/tuple
  - 3
  - 4
  - 9
  width_factor: 1
resnet_pretrained_path: null
skip_channels:
- 512
- 256
- 64
- 16
transformer:
  attention_dropout_rate: 0.0
  dropout_rate: 0.2
  mlp_dim: 3072
  num_heads: 4
  num_layers: 8
```
